{
 "title": "Nodes and Pods (Limits / Requests)",
 "description": "This is a modern 'Pods View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{}, namespace)"
    }
   },
   { "name": "resolution", "query": "15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (node, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval]))) by (node) * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
     "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}})"
    },
    {
     "expr": "avg(sum by (instance,core) (rate(windows_cpu_time_total{mode!=\"idle\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) by (node) / sum(node_memory_MemTotal_bytes{}) by (node)) * 100 * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
     "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}})"
    },
    {
     "expr": "(sum(windows_os_visible_memory_bytes{} - windows_memory_available_bytes{}) by (instance) / sum(windows_os_visible_memory_bytes{}) by (instance)) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_cpu_usage_seconds_total{container_id!=\"\"}[$__rate_interval]) * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\"}) OR kube_namespace_created{} * 0) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace)\n+ on (namespace)\n(sum(windows_container_memory_usage_commit_bytes{container_id!=\"\"} * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\"}) OR kube_namespace_created{} * 0) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Usage / Limits by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod!=\"\", image!=\"\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod!=\"\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage / Limits by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod!=\"\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage / Requests by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod!=\"\", image!=\"\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod!=\"\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod!=\"\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod!=\"\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod!=\"\", image!=\"\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O by instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{}[$__rate_interval])) by (node) * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
       "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}}) read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{}[$__rate_interval])) by (node) * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
       "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}}) write"
      }
     ]
    },
    {
     "title": "Disk Usage by instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(100 - ((node_filesystem_avail_bytes{} * 100) / node_filesystem_size_bytes{})) * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
       "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}}) {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk I/O by namespace",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace!=\"\", pod!=\"\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{ namespace }} read"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace!=\"\", pod!=\"\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{ namespace }} write"
      }
     ]
    },
    {
     "title": "Disk Usage by namespace",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_blkio_device_usage_total{namespace!=\"\"}) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Disk I/O by pod",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} read"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} write"
      }
     ]
    },
    {
     "title": "Disk Usage by pod",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_blkio_device_usage_total{namespace=\"$namespace\", pod!=\"\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bandwidth by instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{}[$__rate_interval])) by (node) * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
       "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}}) rx"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{}[$__rate_interval])) by (node) * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
       "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}}) tx"
      }
     ]
    },
    {
     "title": "Network Packets by instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_packets_total{}[$__rate_interval])) by (node) * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
       "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}}) rx"
      },
      {
       "expr": "sum(rate(node_network_transmit_packets_total{}[$__rate_interval])) by (node) * on(node) group_left(node_short, nodegroup_short, label_kubernetes_io_arch, label_node_kubernetes_io_instance_type, label_tenancy_entigo_com_zone, label_tenancy_entigo_com_zone_pool, label_eks_amazonaws_com_capacity_type, label_topology_kubernetes_io_zone) label_replace(label_replace(kube_node_labels, \"nodegroup_short\", \"$1\", \"label_eks_amazonaws_com_nodegroup\", \"(.+)-[^-]+$\"), \"node_short\", \"$1\", \"node\", \"([^.]+)\\\\..*\")",
       "legendFormat": "{{node_short}} - {{nodegroup_short}} ({{label_node_kubernetes_io_instance_type}} {{label_topology_kubernetes_io_zone}} {{label_kubernetes_io_arch}}) tx"
      }
     ]
    },
    {
     "title": "Network Bandwidth by namespace",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace!=\"\", pod!=\"\"}[$__rate_interval]) * on(namespace, pod) group_left() (kube_pod_info{host_network=\"false\"})) by (namespace)",
       "legendFormat": "{{ namespace }} rx"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace!=\"\", pod!=\"\"}[$__rate_interval]) * on(namespace, pod) group_left() (kube_pod_info{host_network=\"false\"})) by (namespace)",
       "legendFormat": "{{ namespace }} tx"
      }
     ]
    },
    {
     "title": "Network Packets by namespace",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace!=\"\", pod!=\"\"}[$__rate_interval]) * on(namespace, pod) group_left() (kube_pod_info{host_network=\"false\"})) by (namespace)",
       "legendFormat": "{{ namespace }} rx"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace!=\"\", pod!=\"\"}[$__rate_interval]) * on(namespace, pod) group_left() (kube_pod_info{host_network=\"false\"})) by (namespace)",
       "legendFormat": "{{ namespace }} tx"
      }
     ]
    },
    {
     "title": "Network Bandwidth by pod",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod!=\"\"}[$__rate_interval]) * on(namespace, pod) group_left() (kube_pod_info{host_network=\"false\"})) by (pod)",
       "legendFormat": "{{ pod }} rx"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod!=\"\"}[$__rate_interval]) * on(namespace, pod) group_left() (kube_pod_info{host_network=\"false\"})) by (pod)",
       "legendFormat": "{{ pod }} tx"
      }
     ]
    },
    {
     "title": "Network Packets by pod",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\", pod!=\"\"}[$__rate_interval]) * on(namespace, pod) group_left() (kube_pod_info{host_network=\"false\"})) by (pod)",
       "legendFormat": "{{ pod }} rx"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\", pod!=\"\"}[$__rate_interval]) * on(namespace, pod) group_left() (kube_pod_info{host_network=\"false\"})) by (pod)",
       "legendFormat": "{{ pod }} tx"
      }
     ]
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Container Restarts by pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"${namespace}\", pod!=\"\", container!=\"\"}[$__rate_interval])) by (pod, container)",
     "legendFormat": "{{ pod }} {{ container }}"
    }
   ]
  }
 ]
}